services:
    mysql:
      image: mysql:latest
      container_name: mysql_container
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_ROOT_PASSWORD: 
        MYSQL_HOST: localhost
      volumes: 
        - ./docker/mysql:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"